config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :girlfriends, only: [:index, :show, :destroy]

  namespace :account do
    resource :dashboard, only: :show, controller: 'dashboard'
    resources :girlfriends, only: [:index, :show, :new, :create, :destroy] do
      resources :appointments, only: [:new, :create]
    end
    resources :appointments, only: [:index, :show, :new, :create, :destroy]
  end

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  has_one :review

  belongs_to :client, class_name: "User", foreign_key: 'client_id'
  belongs_to :girlfriend
end

app/models/girlfriend.rb
class Girlfriend < ActiveRecord::Base
  belongs_to :pimp, class_name: "User", foreign_key: 'pimp_id'
  has_many :appointments, dependent: :destroy

  geocoded_by :full_address
  after_validation :geocode, if: :full_address_changed?

  has_attached_file :picture,
    styles: { medium: "300x300>", thumb: "100x100>" }

  validates_attachment_content_type :picture,
    content_type: /\Aimage\/.*\z/

  def full_address
    return "#{street}, #{postcode}, #{city}, France"
  end

  def full_address_changed?
    street_changed? || postcode_changed?  || city_changed?
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :appointment
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, omniauth_providers: [:facebook]
  has_many :girlfriends, foreign_key: 'pimp_id'
  has_many :appointments, foreign_key: 'client_id'


   def self.find_for_facebook_oauth(auth)
    user = User.find_by_email(auth.info.email)
    user = where(provider: auth.provider, uid: auth.uid).first_or_create unless user

    user.provider = auth.provider
    user.uid = auth.uid
    user.email = auth.info.email
    user.password = Devise.friendly_token[0,20]  # Fake password for validation
    user.picture = auth.info.image
    user.token = auth.credentials.token
    user.token_expiry = Time.at(auth.credentials.expires_at)
    user.save

    user
  end
end

app/controllers/account/appointments_controller.rb
module Account
  class AppointmentsController < ApplicationController

    def index
      @appointments = current_user.appointments
    end

    def new
      @girlfriend = Girlfriend.find(params[:girlfriend_id])
      @appointment = Appointment.new
    end

    def create
      date = {
        day: params[:appointment]["appointment_on(3i)"].to_i,
        month: params[:appointment]["appointment_on(2i)"].to_i,
        year: params[:appointment]["appointment_on(1i)"].to_i
      }
      @girlfriend = Girlfriend.find(params[:girlfriend_id])
      @appointment = current_user.appointments.new(appoint_params)
      @appointment.girlfriend = @girlfriend

      if @girlfriend.appointments.pluck(:appointment_on).select { |appointment| appointment == Date.new(date[:year], date[:month], date[:day]) }.size > 0

        flash[:alert] = "No more availability for this day"
        render :new


      else
        @appointment.save

        redirect_to account_dashboard_path
      end
    end

    def destroy
      @appointment = current_user.appointments.find(params[:id])
      @appointment.destroy
      redirect_to account_dashboard_path
    end

  private

    def appoint_params
      params.require(:appointment).permit(:appointment_on)

    end
  end
end

app/controllers/account/dashboard_controller.rb
module Account
  class DashboardController < ApplicationController
    def show
      @appointments = current_user.appointments
    end
  end
end

app/controllers/account/girlfriends_controller.rb
module Account
  class GirlfriendsController < ApplicationController

    def index
    end

    def show
      @girlfriend = current_user.girlfriends.find(params[:id])
    end

    def new
     @girlfriend = current_user.girlfriends.new
    end

    def create
      @girlfriend = current_user.girlfriends.new(girlfriend_params)

      if @girlfriend.save
        redirect_to account_girlfriend_path(@girlfriend)
      else
        render :new
      end
    end

    def destroy
      @girlfriend = current_user.girlfriends.find(params[:id])
      @girlfriend.destroy
      redirect_to account_girlfriends_path
    end

  private

    def girlfriend_params
      params.require(:girlfriend).permit(:name, :description, :price, :age, :street, :city, :postcode, :availability, :nationality, :picture, :job)
    end


  # def pimp_id
  #   @pimp = Users.find(params[:id])
  # end

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :authenticate_user!
  protect_from_forgery with: :exception

end

app/controllers/girlfriends_controller.rb
class GirlfriendsController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    if params[:user_input_city]
      @girlfriends = Girlfriend.near(params[:user_input_city], 3)
    else
      @girlfriends = Girlfriend.all
    end

    @hash = Gmaps4rails.build_markers(@girlfriends) do |girlfriend, marker|
      marker.lat girlfriend.latitude
      marker.lng girlfriend.longitude
      marker.infowindow render_to_string(:partial => "/girlfriends/map_box", locals: {girlfriend: girlfriend})
    end
  end

  def show
    @girlfriend = Girlfriend.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @girlfriends = Girlfriend.limit(3)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def failure
    raise
  end

  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/girlfriends_helper.rb
module GirlfriendsHelper
  def top_3_girlfriends
    Girlfriend.limit(3)
  end
end

app/views/girlfriends/_card.html.erb
<div class="card">
  <div class="card-bg" style="background-image:url(<%= girlfriend.picture.url%>)"></div>
  <span class="card-gradient"></span>
  <div class="card-text">
    <h2><%= girlfriend.name %></h2>
  </div>
  <div class="card-price">
    <p><%= girlfriend.price %> € </p>
  </div>

  <% if user_signed_in? %>
    <% if current_user.id == girlfriend.pimp_id %>
      <%= link_to '', account_girlfriend_path(girlfriend), class: "card-link" %>
    <% else %>
      <%= link_to '', new_account_girlfriend_appointment_path(girlfriend), class: "card-link" %>
    <% end %>
  <% else %>
    <%= link_to '', root_path, class: "card-link" %>
  <% end %>
</div>

app/views/girlfriends/_map_box.html.erb
<div class="map_box">
  <h3><%= girlfriend.name %></h3>
  <p><%= girlfriend.street %></p>
  <% if user_signed_in? %>
    <% if current_user.id == girlfriend.pimp_id %>
      <%= link_to 'Wanna meet?', account_girlfriend_path(girlfriend), class: "btn" %>
    <% else %>
      <%= link_to 'Wanna meet?', new_account_girlfriend_appointment_path(girlfriend), class: "btn" %>
    <% end %>
  <% else %>
    <%= link_to 'Wanna meet?', root_path, class: "btn" %>
  <% end %>
</div>

app/views/girlfriends/index.html.erb
<% if params[:user_input_city] %>
  <h1 class="text-center"> Chefs in <%= params[:user_input_city] %> </h1>
<% else %>
  <h1 class="text-center"> Our Chefs </h1>
<% end %>


  <div class="form-group text-center">
    <div class="container">
      <%= form_tag("/girlfriends", method: "get") do %>
        <%= text_field_tag :city, nil, class: "form-control", name: "user_input_city", id: "user_input_city", placeholder: 'Look for another location?' %>
      <% end %>
    </div>
  </div>

  <div class="container">
    <% @girlfriends.each do |girlfriend| %>
      <div class="col-xs-12 col-sm-4">
      <%= render "girlfriends/card", girlfriend: girlfriend %>
      </div>
    <% end %>
  </div>

  <div id="map" style="width: 100%; height: 300px;"></div>

  <% content_for(:after_js) do %>
    <%= javascript_tag do %>
      $(document).on('ready', function() {
        handler = Gmaps.build('Google');
        handler.buildMap({ internal: { id: 'map' } }, function(){
          markers = handler.addMarkers(<%= raw @hash.to_json %>);
          handler.bounds.extendWith(markers);
          handler.fitMapToBounds();
        });
      })
    <% end %>
  <% end %>

app/views/girlfriends/show.html.erb
<div class="container">
  <div class="row col-sm-12 col-md-6 text-center">
      <%= image_tag @girlfriend.picture (:medium) %>
  </div>

  <div class="row col-sm-12 col-md-6 text-center">
    <ul style="list-style: none;">
      <li><strong><%= @girlfriend.name %></strong></li>
      <li><%= @girlfriend.description %></li>
      <li><%= @girlfriend.price %> dollars </li>
      <li><%= @girlfriend.age %> years old </li>
      <li><%= @girlfriend.city %></li>
      <li><%= @girlfriend.street %></li>
      <li><%= @girlfriend.availability %></li>
      <li><%= @girlfriend.nationality %></li>
      <li><%= @girlfriend.job %></li>
  <br>
    </ul>
  </div>


</div>

app/views/layouts/_footer.html.erb
<footer>
  <ul class="text-center social-links list-inline">
    <li>
      <%= link_to 'http://twitter.com/TheoLemaitre' do %>
      <i class="fa fa-instagram"></i>
      <% end %>
    </li>
    <li>
      <%= link_to 'http://facebook.com/theolemaitre' do %>
      <i class="fa fa-facebook"></i>
      <% end %>
    </li>
  </ul>
  <br>
  <p class="credits">
    Made with <i class="fa fa-heart"></i> at Le Wagon
  </p>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar-wagon">
  <div class="container navbar-wagon-container">

    <a href="/">
      <%= image_tag "newlogo.jpg", class: "navbar-wagon-logo" %>
    </a>

    <div class="navbar-wagon-pusher"></div>

    <hr class="hidden-xs hidden-sm">

    <% if user_signed_in? %>
      <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: "navbar-wagon-item navbar-wagon-button btn" %>
    <% else %>
      <%= link_to 'Sign in', new_user_session_path ,class: "navbar-wagon-item navbar-wagon-button btn" %>
    <% end %>

    <hr>

    <% if user_signed_in? %>
      <%= link_to 'Profile', account_dashboard_path ,class: "navbar-wagon-item navbar-wagon-button btn" %>
    <% else %>
      <%= link_to 'Check our chefs', girlfriends_path ,class: "navbar-wagon-item navbar-wagon-button btn" %>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ChefBnb</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Ubuntu:400,300' rel='stylesheet' type='text/css'>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,700|Raleway:400,100,300,700,500">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link href='https://fonts.googleapis.com/css?family=Raleway:400,700' rel='stylesheet' type='text/css'>
</head>
<body>

<%= render 'layouts/navbar' %>

<%= yield %>

<%= javascript_include_tag "https://maps.google.com/maps/api/js?sensor=false" %>
<%= javascript_include_tag "https://google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" %>

<%= javascript_include_tag "application" %>

<%= yield(:after_js) %>

<%= render 'layouts/footer' %>
</body>
</html>

app/views/pages/home.html.erb
<div class='text-center'>

  <div class="banner">
    <div class="banner-shadow"></div>
    <div class="content text-center" data-sr='enter top'>
      <h1> ChefBnb </h1>
      <h3> Pick your Chef </h3>

      <div class="form-group text-center">
        <div class="container">
          <div class="row">
            <div class="col-sm-4 col-sm-offset-4">
              <%= form_tag("/girlfriends", method: "get") do %>
                <%= text_field_tag :city, nil, class: "form-control", name: "user_input_city", id: "user_input_city", placeholder: 'City' %>
                <%= submit_tag "Search", class: 'btn navbar-wagon-button' %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <br>

  <div class="container">
    <div class="col-sm-6 col-md-6">
      <h1> Do you want to learn cooking some fresh organic food with an awesome Chef? </h1>
        <p> Check out all our chef and their recipee. It's a unique experience for all the food lovers. </p>
        <p> All our Chef are CIA and NASA approved (The real cawboys of gastronomy). Stop eating junk food and bring it on! </p>
    </div>
    <div class="embed-container col-sm-6 col-md-6">
      <iframe width="560" height="349" src="http://www.youtube.com/embed/e3YF2GA2YtQ">
        <html lang="en" dir="ltr">
      </iframe>
    </div>
  </div>


  <br>
  <br>
  <br>

  <div class="container">
    <div class="col-sm-12 col-md-6">
    </div>
      <h1> Organic food certified </h1>
      <p> We make sure than the products the chef uses to cook come from local farmers and are organic. Our purpose is to enhance the cooking experience while acting for substainability </p>
  </div>

  <hr>

  <h2><%= link_to 'Our chefs', girlfriends_path, class: "navbar-wagon-item navbar-wagon-button btn" %></h2>

  <div class="container">
    <% @girlfriends.each do |girlfriend| %>
    <div class="col-xs-12 col-sm-4">
      <div class="card text-center" >
        <span class="card-shadow"></span>
        <div class="card-bg" style="background-image:url(<%= girlfriend.picture.url (:medium) %>)"></div>
        <span class="card-text">
          <h2><%= girlfriend.name %></h2>
          <p><%= girlfriend.city %></p>
        </span>
      </div>
    </div>
    <% end %>
  </div>
</div>
</div>